[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
prereqs = "8WgvuFLgrEbat7G3sMH2FhgtEUARm7cW8xmAt2fRYRRJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcusmattus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
